# Generated by Django 4.1.7 on 2023-03-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리 이름', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.IntegerField(default=0, help_text='0: 일반 게시물, 1: 카드 게시물')),
                ('title', models.CharField(help_text='게시물 제목', max_length=50)),
                ('content', models.TextField(help_text='게시물 내용')),
                ('bg_color', models.CharField(default='#FFFFFF', help_text='카드 배경색 (HEX)', max_length=10)),
                ('text_color', models.CharField(default='#333333', help_text='카드 글자색 (HEX)', max_length=10)),
                ('thumbnail', models.CharField(default='', help_text='게시글 썸네일', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='답글 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('comment', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='답글 작성 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('reply', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reply')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='답글 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reply_like',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('post', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='게시물 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_like',
            },
        ),
        migrations.CreateModel(
            name='LinkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.IntegerField(default=0, help_text='0: Github / 1: blog -> 추후 업데이트 예정')),
                ('url', models.CharField(help_text='링크 url', max_length=255)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'link_list',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('comment', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='댓글 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_like',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, default=1, help_text='댓글 작성 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
