# Generated by Django 4.1.7 on 2023-03-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리 이름', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.IntegerField(default=0, help_text='0: 일반 게시물, 100: 카드 게시물')),
                ('title', models.CharField(help_text='게시물 제목', max_length=50)),
                ('content', models.TextField(help_text='게시물 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='답글 내용')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('comment', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=10)),
                ('email', models.CharField(help_text='이메일', max_length=50)),
                ('password', models.CharField(help_text='비밀번호', max_length=20)),
                ('profile_img', models.CharField(help_text='프로필 이미지', max_length=255)),
                ('about', models.CharField(help_text='내 소개', max_length=50)),
                ('blog_name', models.CharField(help_text='블로그 이름', max_length=20)),
                ('access_level', models.BooleanField(default=True, help_text='접근 권한 - True: 접속 가능 / False: 접속 불가')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('reply', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reply')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='답글 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(blank=True, default=1, help_text='답글 작성 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('post', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='게시물 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('comment', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('user', models.ForeignKey(blank=True, default=1, help_text='댓글 좋아요한 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, default=1, help_text='댓글 작성 유저', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
