# Generated by Django 4.1.7 on 2023-03-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, help_text='이름', max_length=10, null=True)),
                ('email', models.EmailField(help_text='이메일', max_length=30, unique=True)),
                ('password', models.CharField(help_text='비밀번호', max_length=255)),
                ('profile_img', models.CharField(blank=True, help_text='프로필 이미지', max_length=255, null=True)),
                ('about', models.CharField(blank=True, help_text='내 소개', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, help_text='핸드폰 번호', max_length=13, null=True)),
                ('blog_name', models.CharField(blank=True, help_text='블로그 이름', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='접근 권한 - True: 접속 가능 / False: 접속 불가')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성 일자')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정 일자')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
