# Generated by Django 4.1.7 on 2023-03-26 12:18

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blog_id',
            field=models.CharField(blank=True, help_text='블로그 아이디', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='프로필 이미지', null=True, upload_to='profile_image/%Y/%m'),
        ),
    ]
