# Generated by Django 4.1.7 on 2023-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_url',
            field=models.CharField(default='', help_text='blog url', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.CharField(default='', help_text='github url', max_length=255),
        ),
    ]
