# Generated by Django 4.1.7 on 2023-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_blog_url_user_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', help_text='내 소개', null=True),
        ),
    ]
