# Generated by Django 4.1.7 on 2023-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='', help_text='프로필 이미지', upload_to=''),
        ),
    ]
